### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by researchase** [idom-team/idom#307]
**Bug description**
unable to run material-ui based example on jupyterlab.

when I run idom_jupyter.run(ViewButtonEvents) I get the following error :

```
2021-02-28 01:39:04.363 | ERROR    | idom.core.layout:_render_component:150 - Failed to render ViewButtonEvents(0x7f1963ce6140)
Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f198171c310>
    └ <Thread(Thread-5, started daemon 139747013416512)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f198171c040>
    └ <Thread(Thread-5, started daemon 139747013416512)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-5, started daemon 139747013416512)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-5, started daemon 139747013416512)>
    │    └ <function _spawn_threaded_event_loop.<locals>.run_in_thread at 0x7f1963dc1430>
    └ <Thread(Thread-5, started daemon 139747013416512)>
  File "/home/ashwin/research/venv_dsd/lib/python3.8/site-packages/idom_jupyter/widget.py", line 104, in run_in_thread
    loop.run_until_complete(coro)
    │    │                  └ <coroutine object LayoutWidget._idom_layout_render_loop at 0x7f1963dd8ac0>
    │    └ <function BaseEventLoop.run_until_complete at 0x7f1980963160>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x7f19809630d0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7f1980964c10>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7f1980a0b9d0>
    └ <Handle <TaskWakeupMethWrapper object at 0x7f19639d4c70>(<Future finished result=None>)>
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskWakeupMethWrapper object at 0x7f19639d4c70>(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskWakeupMethWrapper object at 0x7f19639d4c70>(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskWakeupMethWrapper object at 0x7f19639d4c70>(<Future finished result=None>)>
  File "/home/ashwin/research/venv_dsd/lib/python3.8/site-packages/idom_jupyter/widget.py", line 90, in _idom_layout_render_loop
    update = await self._idom_layout.render()
                   │    │            └ <function Layout.render at 0x7f1974951280>
                   │    └ Layout(ViewButtonEvents(0x7f1963ce6140))
                   └ LayoutWidget()
  File "/home/ashwin/research/venv_dsd/lib/python3.8/site-packages/idom/core/layout.py", line 93, in render
    return self._create_layout_update(component)
           │    │                     └ ViewButtonEvents(0x7f1963ce6140)
           │    └ <function Layout._create_layout_update at 0x7f1974951550>
           └ Layout(ViewButtonEvents(0x7f1963ce6140))
  File "/home/ashwin/research/venv_dsd/lib/python3.8/site-packages/idom/core/layout.py", line 124, in _create_layout_update
    new_model = self._render_component(component_state)
                │    │                 └ ComponentState(model={}, path='', component_id=139747025379648, component_obj=ViewButtonEvents(0x7f1963ce6140), event_handler...
                │    └ <function Layout._render_component at 0x7f19749515e0>
                └ Layout(ViewButtonEvents(0x7f1963ce6140))
> File "/home/ashwin/research/venv_dsd/lib/python3.8/site-packages/idom/core/layout.py", line 139, in _render_component
    raw_model = component_state.component_obj.render()
                │               └ <_collections._tuplegetter object at 0x7f1974948670>
                └ ComponentState(model={}, path='', component_id=139747025379648, component_obj=ViewButtonEvents(0x7f1963ce6140), event_handler...
  File "/home/ashwin/research/venv_dsd/lib/python3.8/site-packages/idom/core/component.py", line 58, in render
    return self._function(*self._args, **self._kwargs)
           │    │          │    │        │    └ <member '_kwargs' of 'Component' objects>
           │    │          │    │        └ ViewButtonEvents(0x7f1963ce6140)
           │    │          │    └ <member '_args' of 'Component' objects>
           │    │          └ ViewButtonEvents(0x7f1963ce6140)
           │    └ <member '_function' of 'Component' objects>
           └ ViewButtonEvents(0x7f1963ce6140)
  File "<ipython-input-10-9441af32faff>", line 14, in ViewButtonEvents
    idom.html.pre(json.dumps(event, indent=2)),
    │    │    │              └ None
    │    │    └ <function make_vdom_constructor.<locals>.pre at 0x7f197496dca0>
    │    └ <idom.widgets.html.Html object at 0x7f1974961e20>
    └ <module 'idom' from '/home/ashwin/research/venv_dsd/lib/python3.8/site-packages/idom/__init__.py'>

NameError: name 'json' is not defined
[ ]:
```￼
​
**To reproduce**
Steps to reproduce the behavior:

1. ...I am using jupyterlab 3
2. ...Ubuntu 20.10
3. ...

**Expected behavior**
A clear and concise description of what you expected to happen.
I was hoping to get a button that is same as demo on website
**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by rmorshea** [comment]
It looks like you forgot to copy the `import json` statement at the top of the example.

There's actually a helpful little button at the top that will copy all the code for you:

![image](https://user-images.githubusercontent.com/4041990/109399529-3321ae80-78f8-11eb-963f-97c82d025eb7.jpeg)

**Comment by researchase** [comment]
Apologies for missing the json package, I did not understand the error message. 
on a separate message this module is really awesome, I use plotly dash and I think I have second thoughts of changing to Idom

**Comment by rmorshea** [comment]
No worries. And thanks!

**Comment by researchase** [comment]
I imported the json and ran but I don't have any output or errors :( 
![Screenshot from 2021-03-02 15-28-32](https://user-images.githubusercontent.com/5505550/109631694-36bd6b80-7b6c-11eb-8f86-297187bc1f59.png)

**Comment by rmorshea** [comment]
Do you see anything in the browser's dev console logs?

**Comment by researchase** [comment]
please see the screenshot attached, I could not understand the issue :( 
![Screenshot from 2021-03-05 17-37-20](https://user-images.githubusercontent.com/5505550/110113781-9cfaf600-7dd9-11eb-8fd1-c21fdc6a223f.png)

**Comment by rmorshea** [comment]
What version of `idom_jupyter` are you running? Try upgrade to `idom_jupyter==0.5.1` - there are some fixes in that release that might solve this.

If that still doesn't work, it would be useful if you could try running this in a regular python script (without `idom_jupyter`) to see if the issue persists. If it does then it's something with `idom` if it doesn't then it's a bug in `idom_jupyter`.
