### ISSUE TITLE
File not found error on page refresh (0.28.0)

### ISSUE THREAD

**Issue by rmorshea** [idom-team/idom#389]
With idom 0.28.0[stable] a regression was introduced where refreshing the page yields a `Error: File not found` error. Downgrading to 0.27.0 fixes the issue. 

This appears to be resolved in `main` now, but we should introduce a test to catch this in the future.

_Originally posted by @brentbaum in https://github.com/idom-team/idom/discussions/388_

**Comment by rmorshea** [comment]
@brentbaum @ksmoore17 I'm having trouble reproducing this issue, can you reply with a basic script that does. Once I have that I can write a test to prevent this regression in the future.

**Comment by brentbaum** [comment]
This issue isn't happening on 0.29.0 for me.

**Comment by rmorshea** [comment]
Awesome!

**Comment by acivitillo** [comment]
I am getting this issue again:

```bash
python .\filterable.py
2022-01-16T10:25:37+0100 | INFO | Using SanicServer
[2022-01-16 10:25:37 +0100] [8848] [INFO] Goin' Fast @ http://127.0.0.1:8000
[2022-01-16 10:25:37 +0100] [8848] [WARNING] Sanic tried to use loop.add_signal_handler but it is not implemented on this platform.
[2022-01-16 10:25:37 +0100] [8848] [WARNING] Sanic tried to use loop.add_signal_handler but it is not implemented on this platform.
[2022-01-16 10:25:37 +0100] [8848] [INFO] Starting worker [8848]
[2022-01-16 10:25:45 +0100] - (sanic.access)[INFO][127.0.0.1:60219]: GET http://127.0.0.1:8000/  302 0
[2022-01-16 10:25:45 +0100] [8848] [ERROR] Exception occurred while handling uri: 'http://127.0.0.1:8000/client/index.html'
Traceback (most recent call last):
  File "C:\Users\acivi\AppData\Local\Programs\Python\Python39\lib\site-packages\sanic\static.py", line 87, in _handler
    stats = await stat(file_path)
  File "C:\Users\acivi\AppData\Local\Programs\Python\Python39\lib\site-packages\aiofiles\os.py", line 13, in run
    return await loop.run_in_executor(executor, pfunc)
  File "C:\Users\acivi\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\acivi\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\idom-0.34.0-py3.9.egg\\idom\\client\\index.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\acivi\AppData\Local\Programs\Python\Python39\lib\site-packages\sanic\app.py", line 942, in handle_request
    response = await response
  File "C:\Users\acivi\AppData\Local\Programs\Python\Python39\lib\site-packages\sanic\static.py", line 132, in _handler
    raise FileNotFound(
sanic.exceptions.FileNotFound: File not found
[2022-01-16 10:25:45 +0100] - (sanic.access)[INFO][127.0.0.1:60219]: GET http://127.0.0.1:8000/client/index.html  404 21
```

**Comment by rmorshea** [comment]
Is this specific to the Sanic server implementation or does this occur on other implementations?

**Comment by rmorshea** [comment]
I'm not able to reproduce at the moment. It's possible this is a Windows specific issue. Happy to hop on a call to try and sort this out if the issue persists.

**Comment by rmorshea** [comment]
@acivitillo is this still happening at all?

**Comment by acivitillo** [comment]
There might be some problems with Windows, but this specific one did not
show up anymore.

**Comment by rmorshea** [comment]
I'm going to close this for now. If it comes up again feel free to comment.
