### ISSUE TITLE
ReactJS Invalid Hook Call

### ISSUE THREAD

**Issue by Archmonger** [idom-team/idom#646]
### Current Situation

This error periodically shows client side and will completely break IDOM, but seems to fix itself if clearing browser cache. Something notable is I have never seen this issue when Django-IDOM was using `idom==0.33.0`, but that may just be coincidence.

This is the exception stack shown in browser console.

```js
react-dom.js:8 Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at a (react.js:2:4779)
    at n.useState (react.js:2:6903)
    at react-bootstrap.js:2:44831
    at ql (react-dom.js:6:52870)
    at Uu (react-dom.js:6:60908)
    at gs (react-dom.js:10:10631)
    at ms (react-dom.js:10:933)
    at pf (react-dom.js:10:864)
    at Et (react-dom.js:10:724)
    at xi (react-dom.js:8:10854)
ai @ react-dom.js:8
react-dom.js:10 Uncaught Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at a (react.js:2:4779)
    at n.useState (react.js:2:6903)
    at react-bootstrap.js:2:44831
    at ql (react-dom.js:6:52870)
    at Uu (react-dom.js:6:60908)
    at gs (react-dom.js:10:10631)
    at ms (react-dom.js:10:933)
    at pf (react-dom.js:10:864)
    at Et (react-dom.js:10:724)
    at xi (react-dom.js:8:10854)
client.js:23649 The above error occurred in the <_ImportedElement> component:

    at _ImportedElement (http://127.0.0.1:7575/static/django_idom/client.js:31103:29)
    at ImportedElement (http://127.0.0.1:7575/static/django_idom/client.js:31075:28)
    at Element (http://127.0.0.1:7575/static/django_idom/client.js:31046:20)
    at div
    at StandardElement (http://127.0.0.1:7575/static/django_idom/client.js:31060:28)
    at Element (http://127.0.0.1:7575/static/django_idom/client.js:31046:20)
    at Layout (http://127.0.0.1:7575/static/django_idom/client.js:31034:19)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ client.js:23649
client.js:2691 Uncaught Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at a (react.js:2:4779)
    at n.useState (react.js:2:6903)
    at react-bootstrap.js:2:44831
    at ql (react-dom.js:6:52870)
    at Uu (react-dom.js:6:60908)
    at gs (react-dom.js:10:10631)
    at ms (react-dom.js:10:933)
    at pf (react-dom.js:10:864)
    at Et (react-dom.js:10:724)
    at xi (react-dom.js:8:10854)
```

### Proposed Actions

Determine root cause and develop a solution.

I seem to be semi-frequently able to reproduce this if leaving my webserver running `django-idom` up while putting my Windows 10 machine to sleep for >12 hours.

See https://github.com/idom-team/idom/discussions/610 for the original discussion.

### Work Items

See above.

**Comment by rmorshea** [comment]
It kind of looks like the error here is coming from `react-bootstrap.js` so it might be a problem there? At the very least, we could add an error boundary as the message says to prevent hard-crashes due to issues arising in imported components.

**Comment by rmorshea** [comment]
I'm also not really sure how to debug this at the moment.

**Comment by Archmonger** [comment]
Same here, not entirely certain how to tackle this one. Just wanted to make sure it's documented, we'll probably circle back around to this eventually.

**Comment by rmorshea** [comment]
I'm gonna close and kick back to discussion until there's something tangible to do. We can create a task for the error boundary though.

**Comment by Archmonger** [comment]
@rmorshea I've determined the root cause of this is an unpinned react bootstrap version.

```python
bootstrap = idom.web.module_from_template(
    "react", "react-bootstrap", resolve_exports=True
)
```

This issue can easily be replicated by pinning to `@2.1.1`, loading a web page, then pinning to `@2.1.2`.

So this issue likely occurs only when my browser has a cached version of `boostrap.js`, and then a there happens to be an update to `react-bootstrap`.

**Comment by Archmonger** [comment]
I've had this issue happen again, despite pinned versions within `module_from_template` call. Not sure what the cause is this time.

**Comment by rmorshea** [comment]
What version of IDOM are you on?

**Comment by rmorshea** [comment]
@Archmonger can you update the trace on this when it happens? I think the client source in the problem area has changed since this was posted.

**Comment by Archmonger** [comment]
Will do once it happens again naturally. I haven't confirmed the breaking lines are the same when I force this issue to happen, only that the error code is identical.

**Comment by Archmonger** [comment]
I had it happen today, but this trace log seems slightly different.
```js
react-dom.js:9 TypeError: Cannot read properties of null (reading 'useState')
    at r.useState (react.js:2:6860)
    at react-bootstrap.js:2:44649
    at Ri (react-dom.js:7:19047)
    at Hu (react-dom.js:9:10756)
    at Js (react-dom.js:9:45976)
    at Xs (react-dom.js:9:39741)
    at nf (react-dom.js:9:39672)
    at Fr (react-dom.js:9:39532)
    at lo (react-dom.js:9:36698)
    at en (react-dom.js:7:3242)
Yl @ react-dom.js:9
react-dom.js:7 Uncaught TypeError: Cannot read properties of null (reading 'useState')
    at r.useState (react.js:2:6860)
    at react-bootstrap.js:2:44649
    at Ri (react-dom.js:7:19047)
    at Hu (react-dom.js:9:10756)
    at Js (react-dom.js:9:45976)
    at Xs (react-dom.js:9:39741)
    at nf (react-dom.js:9:39672)
    at Fr (react-dom.js:9:39532)
    at lo (react-dom.js:9:36698)
    at en (react-dom.js:7:3242)
client.js:23649 The above error occurred in the <_ImportedElement> component:

    at _ImportedElement (http://127.0.0.1:7575/static/django_idom/client.js:31225:29)
    at ImportedElement (http://127.0.0.1:7575/static/django_idom/client.js:31202:28)
    at Element (http://127.0.0.1:7575/static/django_idom/client.js:31076:20)
    at StandardElement (http://127.0.0.1:7575/static/django_idom/client.js:31094:28)
    at Element (http://127.0.0.1:7575/static/django_idom/client.js:31076:20)
    at StandardElement (http://127.0.0.1:7575/static/django_idom/client.js:31094:28)
    at Element (http://127.0.0.1:7575/static/django_idom/client.js:31076:20)
    at StandardElement (http://127.0.0.1:7575/static/django_idom/client.js:31094:28)
    at Element (http://127.0.0.1:7575/static/django_idom/client.js:31076:20)
    at Layout (http://127.0.0.1:7575/static/django_idom/client.js:31060:19)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ client.js:23649
client.js:2691 Uncaught TypeError: Cannot read properties of null (reading 'useState')
    at r.useState (react.js:2:6860)
    at react-bootstrap.js:2:44649
    at Ri (react-dom.js:7:19047)
    at Hu (react-dom.js:9:10756)
    at Js (react-dom.js:9:45976)
    at Xs (react-dom.js:9:39741)
    at nf (react-dom.js:9:39672)
    at Fr (react-dom.js:9:39532)
    at lo (react-dom.js:9:36698)
    at en (react-dom.js:7:3242)
```

**Comment by rmorshea** [comment]
GIven the

**Comment by Archmonger** [comment]
@rmorshea Given that this is still happening with preact, do you have any ideas on the cause of this?

This is a major roadblock for using exported react packages.

**Comment by rmorshea** [comment]
The switch to Preact is unrelated (that just what IDOM uses internally). What matters is the [module template](https://github.com/idom-team/idom/blob/main/src/idom/web/templates/react.js#L3) which is still using React and I think it has to remain that way since any component library is going to import `react` and not `preact`. The only reason we're able to use `preact` in IDOM is because we [use an alias](https://github.com/idom-team/idom/blob/main/src/client/snowpack.config.js#L7-L10).

With that said, I discovered that the material-ui examples in the docs broke because it was expecting a particular version of React (was seeing similar error messages to these). As of [idom `0.39.0`](https://idom-docs.herokuapp.com/docs/about/changelog.html#v0-39-0) you can specify `module_from_template("react@the-version", ...)`. It looks like `react-bootstrap` is looking for `18.1.0` but the template is using the latest (`18.2.0`).

**Comment by Archmonger** [comment]
I am getting the same exception when using a pinned react version

```python
bootstrap = idom.web.module_from_template(
    "react@18.1.0", "react-bootstrap@2.4.0", resolve_exports=True
)
```

```js
react-dom.js:9 TypeError: Cannot read properties of null (reading 'useState')
    at n.useState (react.js:2:6785)
    at react-bootstrap.js:2:44649
    at Bi (react-dom.js:7:19481)
    at bu (react-dom.js:9:1575)
    at aa (react-dom.js:9:45971)
    at ua (react-dom.js:9:39715)
    at pf (react-dom.js:9:39646)
    at Ir (react-dom.js:9:39506)
    at co (react-dom.js:9:36651)
    at on (react-dom.js:7:3250)
bl @ react-dom.js:9
react-dom.js:7 Uncaught TypeError: Cannot read properties of null (reading 'useState')
    at n.useState (react.js:2:6785)
    at react-bootstrap.js:2:44649
    at Bi (react-dom.js:7:19481)
    at bu (react-dom.js:9:1575)
    at aa (react-dom.js:9:45971)
    at ua (react-dom.js:9:39715)
    at pf (react-dom.js:9:39646)
    at Ir (react-dom.js:9:39506)
    at co (react-dom.js:9:36651)
    at on (react-dom.js:7:3250)
client.js:23649 The above error occurred in the <_ImportedElement> component:

    at _ImportedElement (http://127.0.0.1:7575/static/django_idom/client.js:31225:29)
    at ImportedElement (http://127.0.0.1:7575/static/django_idom/client.js:31202:28)
    at Element (http://127.0.0.1:7575/static/django_idom/client.js:31076:20)
    at StandardElement (http://127.0.0.1:7575/static/django_idom/client.js:31094:28)
    at Element (http://127.0.0.1:7575/static/django_idom/client.js:31076:20)
    at StandardElement (http://127.0.0.1:7575/static/django_idom/client.js:31094:28)
    at Element (http://127.0.0.1:7575/static/django_idom/client.js:31076:20)
    at StandardElement (http://127.0.0.1:7575/static/django_idom/client.js:31094:28)
    at Element (http://127.0.0.1:7575/static/django_idom/client.js:31076:20)
    at StandardElement (http://127.0.0.1:7575/static/django_idom/client.js:31094:28)
    at Element (http://127.0.0.1:7575/static/django_idom/client.js:31076:20)
    at StandardElement (http://127.0.0.1:7575/static/django_idom/client.js:31094:28)
    at Element (http://127.0.0.1:7575/static/django_idom/client.js:31076:20)
    at Layout (http://127.0.0.1:7575/static/django_idom/client.js:31060:19)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ client.js:23649
client.js:14904 Uncaught TypeError: Cannot read properties of null (reading 'useState')
    at n.useState (react.js:2:6785)
    at react-bootstrap.js:2:44649
    at Bi (react-dom.js:7:19481)
    at bu (react-dom.js:9:1575)
    at aa (react-dom.js:9:45971)
    at ua (react-dom.js:9:39715)
    at pf (react-dom.js:9:39646)
    at Ir (react-dom.js:9:39506)
    at co (react-dom.js:9:36651)
    at on (react-dom.js:7:3250)
client.js:31312 IDOM WebSocket connection lost. Reconnecting in 1 seconds...
client.js:31277 WebSocket connection to 'ws://127.0.0.1:7575/idom/conreq._core.home.components.homepage/?kwargs=%7B%7D' failed: 
mountLayoutWithReconnectingWebSocket @ client.js:31277
client.js:31312 IDOM WebSocket connection lost. Reconnecting in 3 seconds...
client.js:31282 IDOM WebSocket connected.
react-dom.js:9 Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Object.X (react-dom.js:7:19215)
    at n.useState (react.js:2:6785)
    at react-bootstrap.js:2:44811
    at ji (react-dom.js:7:19036)
    at Zu (react-dom.js:9:10853)
    at sa (react-dom.js:9:46246)
    at ia (react-dom.js:9:39943)
    at ff (react-dom.js:9:39874)
    at Fr (react-dom.js:9:39734)
    at co (react-dom.js:9:36883)
ql @ react-dom.js:9
react-dom.js:7 Uncaught Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Object.X (react-dom.js:7:19215)
    at n.useState (react.js:2:6785)
    at react-bootstrap.js:2:44811
    at ji (react-dom.js:7:19036)
    at Zu (react-dom.js:9:10853)
    at sa (react-dom.js:9:46246)
    at ia (react-dom.js:9:39943)
    at ff (react-dom.js:9:39874)
    at Fr (react-dom.js:9:39734)
    at co (react-dom.js:9:36883)
client.js:23649 The above error occurred in the <_ImportedElement> component:

    at _ImportedElement (http://127.0.0.1:7575/static/django_idom/client.js:31225:29)
    at ImportedElement (http://127.0.0.1:7575/static/django_idom/client.js:31202:28)
    at Element (http://127.0.0.1:7575/static/django_idom/client.js:31076:20)
    at StandardElement (http://127.0.0.1:7575/static/django_idom/client.js:31094:28)
    at Element (http://127.0.0.1:7575/static/django_idom/client.js:31076:20)
    at StandardElement (http://127.0.0.1:7575/static/django_idom/client.js:31094:28)
    at Element (http://127.0.0.1:7575/static/django_idom/client.js:31076:20)
    at StandardElement (http://127.0.0.1:7575/static/django_idom/client.js:31094:28)
    at Element (http://127.0.0.1:7575/static/django_idom/client.js:31076:20)
    at StandardElement (http://127.0.0.1:7575/static/django_idom/client.js:31094:28)
    at Element (http://127.0.0.1:7575/static/django_idom/client.js:31076:20)
    at StandardElement (http://127.0.0.1:7575/static/django_idom/client.js:31094:28)
    at Element (http://127.0.0.1:7575/static/django_idom/client.js:31076:20)
    at Layout (http://127.0.0.1:7575/static/django_idom/client.js:31060:19)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ client.js:23649
client.js:2691 Uncaught Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Object.X (react-dom.js:7:19215)
    at n.useState (react.js:2:6785)
    at react-bootstrap.js:2:44811
    at ji (react-dom.js:7:19036)
    at Zu (react-dom.js:9:10853)
    at sa (react-dom.js:9:46246)
    at ia (react-dom.js:9:39943)
    at ff (react-dom.js:9:39874)
    at Fr (react-dom.js:9:39734)
    at co (react-dom.js:9:36883)
```

**Comment by Archmonger** [comment]
Ironically, it seems like the issue is even worse now. I can't get my react-bootstrap exports to work at all now. Even after clearing cache, the issue persists.

**Comment by Archmonger** [comment]
Since I seem to be able to replicate this with 100% consistency now, I've configured the Conreq repo in a way that you can test this out on your side.

1) Pull down the `archmonger/conreq@app_store` branch from GitHub
2) `pip install -r requirements.txt`
3) `python manage.py run_conreq`
4) Remove the following `return div()`: https://github.com/Archmonger/Conreq/blob/633d79e0002bedcdb40d9e01bb1d60a0ba0af603/conreq/_core/home/components/modal.py#L29

**Comment by Archmonger** [comment]
Closing this in favor of #786
